---
title: "Simulations for Norm Estimation by Sampling"
author: "Lucia Vilallonga"
output: html_notebook
---

## Set Up
```{r}
library(psych)        # for the trace method
library(matrixcalc)   # for matrix.power function
library(insight)      # for table
library(ggplot2)      # for plots
library(purrr)        # for has_element function

theme_set(theme_minimal())
```

## Methods
```{r}
# A method to draw a random test matrix with isotropic column vectors.
# Recall that:
#  * an isotropic vector w is one with the property E[w %*% t(w)] = I
#
# Parameters
# ----------
# n :  int
#      The number of rows
# k :  int
#      The number of columns
#
# Returns
# -------
# O :  matrix()
#      The test matrix
#
drawTestM <- function(n, k) {
  
  O <- NULL # matrix(0, nrow=n, ncol=k)
  
  for(i in 1:k) {
    # Draw an isotropic column vector, eg. from the Gaussian distr. with variance=1
    col <- matrix(rnorm(n, mean=0, sd=1), nrow=n, ncol=1)
    O <- cbind(O, col)
  }
  
  return(O)
}
```

```{r}
# A method to compute the true (l-2p)^2p norm of a matrix, to compare with the estimate.
#
# Parameters
# ----------
# A :  matrix()
#      The nxm matrix for which to compute the norm
#
# Returns
# -------
# nrm : double
#       The (l-2p)^2p norm of the input matrix   
#
computeNorm <- function(A, p) {
  n <- nrow(A)
  m <- ncol(A)
  
  sing_vals <- svd(A)$d
  nrm <- 0
  
  for(i in 1:min(m,n)) {
    nrm <- nrm + (sing_vals[i]^(2*p))
  }
  
  nrm <- nrm^(1/(2*p))
  
  return(nrm^(2*p))
}
```

```{r}
# A method to compute an unbiased estimator for the l-2p norm of a matrix.
# The method uses: a random test matrix (see drawTestM()); matrix-vector multiplication; 
# and a linear map from the space of self-adjoint square matrices to 
# the space of general square upper triangular matrices.
# Recall that:
#  * the l-2p norm of a matrix is the 2p-root sum of its elements^2p
#  * an unbiased estimator has an expected value equal to the quantity to be estimated
#  * an isotropic vector w is one with the property E[w %*% t(w)] = I
# For proof that this method does produce an unbiased estimator for the l-2p norm of a
# matrix, please see the accompanying proofs.pdf file.
#
# Parameters
# ----------
# B :  matrix()
#      The mxn matrix for which to estimate the l-2p norm
# p :  int
#      The power >0 of the norm
# k :  int
#      The number of samples to take
#
# Returns
# -------
# V : double
#     The estimate of the l-2p norm
#
schattenEstimate <- function(B, p, k) {
  m <- nrow(B)
  n <- ncol(B)
  
  O <- drawTestM(n, k)  # draw the test matrix (nxk)
  Y <- B %*% O          # compute the sample matrix (mxk)
  X <- t(Y) %*% Y       # compute the Gram matrix (kxk)   

  # Extract the strict upper triangle of X  
  T_p <- X
  T_p[lower.tri(T_p)] <- 0  # set the lower triangle to 0
  diag(T_p) <- 0            # set the diagonals to 0
  
  # Compute T^(p-1) 
  T_p <- matrix.power(T_p, (p-1)) 
  
  # Compute and return the estimate of the norm
  V <- (1/choose(k, p)) * tr(T_p %*% X) 
  return(V)
}
```

```{r}
# A method to compute the error of the estimate as compared to the true value.
# 
# Parameters
# ----------
# a,b  :  list 
#         The two lists to compare
# 
# Returns
# -------
# errs :  list
#         The absolute errors for each element in the lists ($abs), 
#         the mean error ($avg),  
#         and the mean squared error ($mse)
#
computeErr <- function(a, b) {
  
  abs <- matrix(0, nrow=1, ncol=length(a))
  avg <- 0
  rms <- 0
  
  # Compute the absolute error
  for(i in 1:length(a)) {
    abs[i] <- abs(a[[i]] - b[[i]])
  }
  
  # Compute the mean error
  sum <- sum(abs)
  avg <- sum / length(a)
  
  # Compute the root mean squared error (RMSE)
  for(i in 1:length(a)) {
    rms[i] <- sqrt((a[[i]] - b[[i]])^2) / length(a)
  }
  
  return(list("abs" = abs, "avg" = avg, "rms" = rms))
}             
```

## Simulation: Is the Estimate Faster? How Accurate is it?
```{r}
set.seed(987654321)

# Fix m = 1000, n = 2000
n <- 1000
m <- 2000

# Set up varying values for p (the power of the norm) and k (the number of samples)
P <- seq(1, 100)
K <- seq(100, 1000, by=50) 

A <- matrix(rnorm(m*n), nrow=m, ncol=n)  # generate a random mxn matrix for the simulation

# Create a dataframe for the results
results <- data.frame(matrix(ncol=7, nrow=length(P) * length(K)))
colnames(results) <- c("p", "k", "Estimate", "TrueValue", "RMSE", "RuntimeEst", "RuntimeTrue")

index_true <- 1
index_est  <- 1

for(p in P) {
  
  # Compute the true Schatten-2p norm and record the runtime
  start <- Sys.time()
  
  norm_true <- computeNorm(A, p)
  runtime   <- Sys.time() - start
  
  # Record the true value and run time in the next length(K) rows
  for(i in index_true:(index_true + length(K) - 1)) {
    results[i, "RuntimeTrue"] <- runtime
    results[i, "TrueValue"]   <- norm_true
  }
  
  index_true <- index_true + length(K)
  
  # Compute the estimate of the Schatten-2p norm for each number of samples k and record the runtime
  for(k in K) {
    results[index_est, "p"] <- p
    results[index_est, "k"] <- k

    # Compute the estimate of the Schatten-2p norm and record the runtime
    new_start <- Sys.time()
  
    norm_est <- schattenEstimate(A, p, k)
    results[index_est, "RuntimeEst"] <- Sys.time() - new_start
    results[index_est, "Estimate"]   <- norm_est
  
    index_est <- index_est + 1
  }
}

# Compute the errors
for(i in 1:nrow(results)) {
  results[i, "RMSE"] <- computeErr(results[i, "Estimate"], results[i, "TrueValue"])$rms
}
```

## Plot the Results
```{r}
# First, need to clean up a little bit - some values are NaN, some RMSE are Inf, and
# for large values of p the norm is Inf

results_clean <- data.frame(results)
results_clean <- na.omit(results_clean)   # drop NaN rows

# Drop rows with Inf norm values -- keep Inf RMSE rows for now
results_clean <- subset(results_clean, Estimate != "-Inf") 
results_clean <- subset(results_clean, Estimate != "Inf") 
results_clean <- subset(results_clean, TrueValue != "Inf")

nrow(results) - nrow(results_clean)  # dropped this many rows

results_err <- subset(results_clean, RMSE != "Inf")  # keep a separate df for non-Inf RMSE

# Save everything
write.csv(results, file="~/bu/year3/spring/ma589/comp-stats-sims/final-project/norm-estim/results_raw.csv")
write.csv(results_clean, file="~/bu/year3/spring/ma589/comp-stats-sims/final-project/norm-estim/results_clean.csv")
write.csv(results_err, file="~/bu/year3/spring/ma589/comp-stats-sims/final-project/norm-estim/results_err.csv")

# Why did the sampling method output NaN, 0, or +/-Inf? Try again for some examples:
schattenEstimate(A, 56, 400)  # still NaN
schattenEstimate(A, 58, 200)  # still Inf
schattenEstimate(A, 68, 700)  # still 0
```

```{r}
# If needed to clean up and "sweep", run the following lines:
results_clean <- read.csv("./results_clean.csv")
results_err   <- read.csv("./results_err.csv")

fivenum(results_err$RMSE)

# Plot of RMSE vs k for estimate
ggplot(results_err, aes(x=k, y=RuntimeEst)) +
  geom_point(aes(x=k, y=RMSE), size=1) +
  ggtitle(label="RMSE vs Number of Samples") +
  xlab("Samples") +
  ylab("") +
  theme(axis.line=element_line(color="black"))

ggplot(results_err, aes(x=k, y=RuntimeEst)) +
  geom_point(aes(x=k, y=RMSE), size=1) +
  scale_y_continuous(limits=c(0, 1e9)) +
  ggtitle(label="RMSE vs Number of Samples (Zoomed)") +
  xlab("Samples") +
  ylab("")
  theme(axis.line=element_line(color="black"))

# Plot of RMSE vs p for estimate
ggplot(results_err, aes(x=p, y=RuntimeEst)) +
  geom_point(aes(x=p, y=RMSE), size=1) +
  ggtitle(label="RMSE vs Norm Power") +
  xlab("Power") +
  ylab("") +
  theme(axis.line=element_line(color="black"))

ggplot(results_err, aes(x=p, y=RuntimeEst)) +
  geom_point(aes(x=k, y=RMSE), size=1) +
  scale_y_continuous(limits=c(0, 5e8)) +
  ggtitle(label="RMSE vs Norm Power (Zoomed)") +
  xlab("Power") +
  ylab("") +
  theme(axis.line=element_line(color="black"))


# Plot of runtime vs k for estimate, with runtime of direct method for comparison
ggplot(results_clean, aes(x=k, y=RuntimeEst)) +
  geom_point(color="#46CC6D", size=1) +
  geom_line(aes(y=RuntimeTrue, color="#6E6A73"), linetype="dashed") +
  ggtitle(label="Runtimes vs Number of Samples") +
  ylab("Time (s)") +                                                         
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#6E6A73"), labels=c("Direct method")) +
  theme(axis.line=element_line(color="black"))


# Plot of runtime vs p for estimate, with runtime of direct method for comparison
ggplot(results_clean, aes(x=p, y=RuntimeEst)) +
  geom_point(aes(color="#46CC6D"), size=1, show.legend=TRUE) +
  geom_line(aes(y=RuntimeTrue, color="#6E6A73"), linetype="dashed") +
  ggtitle(label="Runtimes vs Norm Power") +
  ylab("Time (s)") +                                                         
  xlab("Power") +
  scale_color_manual(name="Legend", values=c("#46CC6D", "#6E6A73"), labels=c("Sampling method", "Direct method")) +
  theme(axis.line=element_line(color="black"))

ggplot(results_clean, aes(x=p, y=RuntimeEst, color=factor(k))) +
  geom_point(size=0.5) +
  ggtitle(label="Runtimes vs Norm Power", subtitle="Colored by number of samples") +
  ylab("Time (s)") +                                                         
  xlab("Power") +
  theme(axis.line=element_line(color="black"), legend.position="bottom", legend.title=element_blank())


# Quantiles by p
quantiles <- fivenum(results_clean[,"p"])  
q1 <- subset(results_clean, p == quantiles[1])

# Plot of estimate for first quantile vs samples
ggplot(q1, aes(x=k, y=Estimate)) +
  geom_point(color="#F46431", size=0.5) +
  geom_line(aes(x=k, y=Estimate), color="#F46431") +
  geom_line(aes(x=k, y=TrueValue, color="#6E6A73"), linetype="dashed") +
  scale_color_manual(name="Legend", values=c("#6E6A73"), labels=c("True Value")) +
  ggtitle("Norm Estimate vs Number of Samples", subtitle="First quantile, p = 1") +
  xlab("Samples") +
  ylab("") +
  theme(axis.line=element_line(color="black"))


# Histogram of estimates
ggplot(q1, aes(x=Estimate)) +
  geom_histogram(binwidth=200, fill="#3C70CA") +
  geom_vline(aes(xintercept=TrueValue, color="#6E6A73"), linetype="dashed") +
  ggtitle("Histogram of Estimates", subtitle="First quantile, p = 1") +
  xlab("Value") +
  ylab("") +
  scale_color_manual(name="Legend", values=c("#6E6A73"), labels=c("True Value")) +
  theme(axis.line=element_line(color="black"))
```

```{r}
# UNUSED PLOTS

q2 <- subset(results_clean, p == quantiles[2])
q3 <- subset(results_clean, p == quantiles[3])
q4 <- subset(results_clean, p == quantiles[4])
q5 <- subset(results_clean, p == quantiles[5])
qs <- rbind(q1, q2, q3, q4, q5)

ggplot(q2, aes(x=k, y=Estimate)) +
  geom_point(aes(color="#F46431"), size=0.5) +
  geom_line(aes(x=k, y=Estimate, color="#F46431")) +
  geom_line(aes(x=k, y=TrueValue), color="#6E6A73", linetype="dashed") +
  scale_color_manual(name="Legend", values=c("#F46431", "#6E6A73"), labels=c("Estimate", "True Value")) +
  ggtitle("Value vs Number of Samples: Estimate vs True", subtitle="Second quantile, p = 18") +
  xlab("Samples") +
  ylab("") +
  theme(axis.line=element_line(color="black"))

ggplot(q3, aes(x=k, y=Estimate)) +
  geom_point(aes(color="#F46431"), size=0.5) +
  geom_line(aes(x=k, y=Estimate, color="#F46431")) +
  geom_line(aes(x=k, y=TrueValue), color="#6E6A73", linetype="dashed") +
  scale_color_manual(name="Legend", values=c("#F46431", "#6E6A73"), labels=c("Estimate", "True Value")) +
  ggtitle("Value vs Number of Samples: Estimate vs True", subtitle="Third quantile, p = 35") +
  xlab("Samples") +
  ylab("") +
  theme(axis.line=element_line(color="black"))

ggplot(q4, aes(x=k, y=Estimate)) +
  geom_point(aes(color="#F46431"), size=0.5) +
  geom_line(aes(x=k, y=Estimate, color="#F46431")) +
  geom_line(aes(x=k, y=TrueValue), color="#6E6A73", linetype="dashed") +
  scale_color_manual(name="Legend", values=c("#F46431", "#6E6A73"), labels=c("Estimate", "True Value")) +
  ggtitle("Value vs Number of Samples: Estimate vs True", subtitle="Third quantile, p = 35") +
  xlab("Samples") +
  ylab("") +
  theme(axis.line=element_line(color="black"))

ggplot(q5, aes(x=k, y=Estimate)) +
  geom_point(aes(color="#F46431"), size=0.5) +
  geom_line(aes(x=k, y=Estimate, color="#F46431")) +
  geom_line(aes(x=k, y=TrueValue), color="#6E6A73", linetype="dashed") +
  scale_color_manual(name="Legend", values=c("#F46431", "#6E6A73"), labels=c("Estimate", "True Value")) +
  ggtitle("Value vs Number of Samples: Estimate vs True", subtitle="Third quantile, p = 35") +
  xlab("Samples") +
  ylab("") +
  theme(axis.line=element_line(color="black"))


ggplot(q1, aes(x=Estimate)) +
  geom_freqpoly(binwidth=500, color="#3C70CA") +
  geom_vline(xintercept=q1$TrueValue, linetype="dashed", color="#6E6A73") +
  theme(axis.line=element_line(color="black"))

ggplot(q2, aes(x=Estimate, color=p)) +
  geom_freqpoly(binwidth=1e62) +
  geom_vline(xintercept=q2$TrueValue, linetype="dashed", color=p)

ggplot(q2, aes(x=Estimate, fill=p)) +
  geom_histogram(binwidth=1e62) +
  geom_vline(xintercept=q2$TrueValue, linetype="dashed", color=p)

```