---
title: "Simulations for Trace Estimation by Sampling"
author: "Lucia Vilallonga"
output:
  html_document:
    df_print: paged
---

## Set Up
```{r}
library(ggplot2)
```

## Methods
```{r}
# A method to compute an unbiased estimator for the trace of a psd matrix. 
# The method uses a random isotropic test vector and matrix-vector 
# multiplication to produce the estimator for the trace. 
# Recall that:
#  * the trace of a square matrix is the sum of its diagonal elements
#  * an unbiased estimator has an expected value equal to the quantity to be estimated
#  * an isotropic vector w is one with the property E[w %*% t(w)] = I
# For proof that this method does produce an unbiased estimator for the trace of a psd
# matrix, please see the accompanying proofs.pdf file.
#
# Parameters
# ----------
# A :  matrix()
#      The nxn psd matrix for which to estimate the trace
# k :  integer
#      The number of samples to take
#
# Returns
# -------
# values$X :  double
#             The estimate of trace(A)
# values$S :  double
#             The sample variance of the estimate
#
traceEstimate <- function(A, k) {
  assertthat::is.count(k)
  
  samples <- matrix(0, nrow=k, ncol=1)
  
  for(i in 1:k) {
    # Draw the isotropic test vector, eg. from the Gaussian distr. with variance=1
    test_vector <- matrix(rnorm(n, mean=0, sd=1), nrow=n, ncol=1)  
    
    # Compute the sample of the estimate and add it to the list
    sample <- t(test_vector) %*% (A %*% test_vector)
    samples[i] <- sample
  }
  
  estimate <- (1/k) * sum(samples)                     # compute the estimate
  var      <- (1/(k-1)) * sum((samples - estimate)^2)  # compute the variance
  
  return(list("X" = estimate, "S" = var))
}
```

```{r}
# A method to compute the true trace of a matrix, for comparison with the RandNLA method.
#
# Parameters
# ----------
# A :  matrix()
#      The nxn psd matrix for which to compute the trace
#
# Returns
# -------
# tr : double
#      The trace of the input matrix
#
trace <- function(A) {
  n <- nrow(A)
  tr <- 0
  
  for(i in 1:n) {
    tr <- tr + A[i,i]
  }
  
  return(tr)
}
```

```{r}
# A method to compute the error of the estimate as compared to the true value.
# 
# Parameters
# ----------
# a,b  :  list 
#         The two lists to compare
# 
# Returns
# -------
# errs :  list
#         The absolute errors for each element in the lists ($abs), 
#         the mean error ($avg),  
#         and the mean squared error ($mse)
#
compute_err <- function(a, b) {
  
  abs <- matrix(0, nrow=1, ncol=length(a))
  avg <- 0
  rms <- 0
  
  # Compute the absolute error
  for(i in 1:length(a)) {
    abs[i] <- abs(a[[i]] - b[[i]])
  }
  
  # Compute the mean error
  sum <- sum(abs)
  avg <- sum / length(a)
  
  # Compute the root mean squared error (RMSE)
  for(i in 1:length(a)) {
    rms[i] <- sqrt((a[[i]] - b[[i]])^2) / length(a)
  }
  
  return(list("abs" = abs, "avg" = avg, "rms" = rms))
}
```

## Simulation: Is the Estimate Faster? How Accurate is it?
```{r}
set.seed(987654321)

N <- seq(from=1, to=50)
K <- seq(from=2, to=100)

# Create a data frame with the results
results <- data.frame(matrix(ncol=9, nrow=length(N) * length(K)))
colnames(results) <- c("n", "k", "Estimate", "TrueValue", "RMSE", "RuntimeEst", "RuntimeTrue", "SampleVariance", "SampleStdDev")

index_true <- 1
index_est  <- 1

for(n in N) {
  # Generate a random psd matrix for the simulation
  A <- matrix(rnorm(n*n), nrow=n, ncol=n)
  A <- A %*% t(A)
  
  # Compute the true trace and record the runtime
  start <- Sys.time()
  
  trace_true <- trace(A)
  runtime    <- Sys.time() - start
  
  # Record the true value and run time in the next length(K) rows
  for(i in index_true:(index_true + length(K) - 1)) {
    results[i, "RuntimeTrue"] <- runtime
    results[i, "TrueValue"]     <- trace_true
  }
  
  index_true <- index_true + length(K)
  
  for(k in K) {
    results[index_est, "n"]    <- n
    results[index_est, "k"] <- k

    # Compute the estimate of the trace and record the runtime
    new_start <- Sys.time()
  
    trace_est <- traceEstimate(A, k)
    results[index_est, "RuntimeEst"] <- Sys.time() - new_start
    results[index_est, "Estimate"]       <- trace_est$X

    results[index_est, "SampleVariance"]  <- trace_est$S
    results[index_est, "SampleStdDev"] <- sqrt(as.double(trace_est$S))
  
    index_est <- index_est + 1
  }
}

# Compute the errors
for(i in 1:nrow(results)) {
  results[i, "RMSE"] <- compute_err(results[i, "Estimate"], results[i, "TrueValue"])$rms
}
```

## Plotting the Results
```{r}
# Plot of trace estimate vs number of samples 
# Examples: n=2, n=25, n = 50
example1 <- results[100:198,]
example2 <- results[2377:2475,]
example3 <- results[4852:4950,]

ggplot(example1, aes(x=k, y=Estimate)) +
  geom_point(aes(color="#2160ad"), size=1, show.legend=TRUE) +
  geom_line(aes(color="#2160ad")) +
  geom_line(aes(y=2.363978, color="#6E6A73"), linetype="dotdash", show.legend=TRUE) +
  ggtitle(label="Trace Estimate vs Number of Samples", subtitle="For a psd matrix with n=2 rows") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#2160ad", "#6E6A73"), labels=c("Estimate of the trace", "True value of the trace"))

ggplot(example2, aes(x=k, y=Estimate)) +
  geom_point(aes(color="#2160ad"), size=1, show.legend=TRUE) +
  geom_line(aes(color="#2160ad")) +
  geom_line(aes(y=599.3642, color="#6E6A73"), linetype="dotdash", show.legend=TRUE) +
  ggtitle(label="Trace Estimate vs Number of Samples", subtitle="For a psd matrix with n=25 rows") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#2160ad", "#6E6A73"), labels=c("Estimate of the trace", "True value of the trace"))

ggplot(example3, aes(x=k, y=Estimate)) +
  geom_point(aes(color="#2160ad"), size=1, show.legend=TRUE) +
  geom_line(aes(color="#2160ad")) +
  geom_line(aes(y=example3[2, "TrueValue"], color="#6E6A73"), linetype="dotdash", show.legend=TRUE) +
  ggtitle(label="Trace Estimate vs Number of Samples", subtitle="For a psd matrix with n=50 rows") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#2160ad", "#6E6A73"), labels=c("Estimate of the trace", "True value of the trace"))


# Plot of RMSE vs number of samples
ggplot(results, aes(x=k, y=RMSE)) +
  geom_point(size=0.5) +
  ggtitle("RMSE vs Number of Samples") +
  xlab("Samples")


# Plot of RMSE vs number of rows
ggplot(results, aes(x=n, y=RMSE)) +
  geom_point(size=0.5) +
  ggtitle("RMSE vs Number of Rows") +
  xlab("Rows")


# Plot of runtimes vs number of samples for n=2, 25, and 50
ggplot(example1, aes(x=k, y=RuntimeEst)) +
  geom_point(aes(color="#46CC6D"), size=1, show.legend=TRUE) +                                    # example 1
  geom_point(data=example2, aes(x=k, y=RuntimeEst, color="#2993EC"), size=1, show.legend=TRUE) +  # example 2
  geom_point(data=example3, aes(x=k, y=RuntimeEst, color="#EA6596"), size=1, show.legend=TRUE) +  # example 3
  ggtitle(label="Runtimes vs Number of Samples", subtitle="For a psd matrix with 2, 25, and 50 rows") +
  ylab("Runtime (s)") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#46CC6D", "#2993EC", "#EA6596"), labels=c("2 rows", "25 rows", "50 rows"))

# Plot of runtimes vs number of samples for n=2, with base method comparison
ggplot(example1, aes(x=k, y=RuntimeEst)) +
  geom_point(aes(color="#46CC6D"), size=1, show.legend=TRUE) +
  geom_point(aes(x=k, y=RuntimeTrue, color="#6E6A73"), size=0.2, show.legend=TRUE) +
  geom_line(aes(y=RuntimeTrue, color="#6E6A73"), linetype="dashed") +
  ggtitle(label="Runtimes vs Number of Samples: Estimate vs Direct Method", subtitle="For a psd matrix with n=2 rows") +
  ylab("Runtime (s)") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#46CC6D", "#6E6A73"), labels=c("Sampling method", "Direct method"))

# Plot of runtimes vs number of samples for n=25, with base method comparison
ggplot(example2, aes(x=k, y=RuntimeEst)) +
  geom_point(aes(color="#2993EC"), size=1, show.legend=TRUE) +
  geom_point(aes(x=k, y=RuntimeTrue, color="#6E6A73"), size=0.2, show.legend=TRUE) +
  geom_line(aes(y=RuntimeTrue, color="#6E6A73"), linetype="dashed") +
  ggtitle(label="Runtimes vs Number of Samples: Estimate vs Direct Method", subtitle="For a psd matrix with n=25 rows") +
  ylab("Runtime (s)") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#2993EC", "#6E6A73"), labels=c("Sampling method", "Direct method"))

# Plot of runtimes vs number of samples for n=50, with base method comparison
ggplot(example3, aes(x=k, y=RuntimeEst)) +
  geom_point(aes(color="#EA6596"), size=1, show.legend=TRUE) +
  geom_point(aes(x=k, y=RuntimeTrue, color="#6E6A73"), size=0.2, show.legend=TRUE) +
  geom_line(aes(y=RuntimeTrue, color="#6E6A73"), linetype="dashed") +
  ggtitle(label="Runtimes vs Number of Samples: Estimate vs Direct Method", subtitle="For a psd matrix with n=50 rows") +
  ylab("Runtime (s)") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#EA6596", "#6E6A73"), labels=c("Sampling method", "Direct method"))

# Combined plot of runtimes vs number of samples with base method comparison
ggplot(example1, aes(x=k, y=RuntimeEst)) +
  geom_point(data=example1, aes(color="#46CC6D"), size=1, show.legend=TRUE) +
  geom_point(data=example2, aes(color="#2993EC"), size=1, show.legend=TRUE) +
  geom_point(data=example3, aes(color="#EA6596"), size=1, show.legend=TRUE) +
  geom_line(aes(y=RuntimeTrue, color="#6E6A73"), linetype="dashed") +
  ggtitle(label="Runtimes vs Number of Samples: Estimate vs Direct Method") +
  ylab("Runtime (s)") +
  xlab("Samples") +
  scale_color_manual(name="Legend", values=c("#46CC6D", "#2993EC", "#EA6596", "#6E6A73"), labels=c("Sampling method, n=2", "Sampling method, n=25", "Sampling method, n=50", "Direct method"))
```
